# Generated by Django 3.1.5 on 2021-02-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmodule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='register',
            name='rating',
            field=models.CharField(default='rating', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='remarks',
            field=models.CharField(default='remarks', max_length=255),
        ),
    ]
