# Generated by Django 3.1.5 on 2021-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmodule', '0002_auto_20210213_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='register',
            name='remarks',
        ),
    ]
